/**
 * ═══════════════════════════════════════════════════════════════
 *  VANTAGE — Dossier rendering
 *
 *  Renders an investigation (or an AOI snapshot) into a shareable
 *  intelligence dossier. Markdown is the source of truth; the HTML view
 *  carries print CSS so the browser's own "Save as PDF" produces the PDF
 *  without dragging a headless Chromium into the image.
 *
 *  ponytail: Markdown + print-CSS instead of a PDF library. Add a real PDF
 *  renderer only if the browser export proves insufficient.
 * ═══════════════════════════════════════════════════════════════
 */

export interface GraphNode {
  id: string;
  label: string;
  type: string;
  /** Free-form attributes surfaced in the dossier entity table. */
  attrs?: Record<string, string | number | boolean | null>;
  sanctioned?: boolean;
}

export interface GraphLink {
  source: string;
  target: string;
  label?: string;
}

export interface InvestigationGraph {
  nodes: GraphNode[];
  links: GraphLink[];
}

export interface DossierInput {
  name: string;
  graph: InvestigationGraph;
  notes?: string;
  /** Narrative produced by the AI copilot, if the operator asked for one. */
  assessment?: string;
  generatedAt?: string;
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function dtg(iso: string): string {
  // Date-Time Group, the notation the rest of the HUD already uses.
  return new Date(iso).toISOString().replace('T', ' ').replace(/\.\d+Z$/, 'Z');
}

export function renderMarkdown(input: DossierInput): string {
  const generatedAt = input.generatedAt ?? new Date().toISOString();
  const { nodes, links } = input.graph;
  const sanctioned = nodes.filter((n) => n.sanctioned);

  const out: string[] = [];
  out.push(`# VANTAGE DOSSIER — ${input.name}`);
  out.push('');
  out.push('**Classification:** OPEN SOURCE INTELLIGENCE (OSINT)  ');
  out.push(`**DTG:** ${dtg(generatedAt)}  `);
  out.push(`**Entities:** ${nodes.length} · **Relationships:** ${links.length}`);
  out.push('');

  out.push('## I. BOTTOM LINE UP FRONT');
  out.push('');
  if (input.assessment?.trim()) {
    out.push(input.assessment.trim());
  } else {
    out.push(
      `Investigation "${input.name}" maps ${nodes.length} entities across ${links.length} relationships.` +
        (sanctioned.length
          ? ` ${sanctioned.length} entity(ies) match the OFAC SDN list — see Section IV.`
          : ' No OFAC SDN matches among the mapped entities.')
    );
  }
  out.push('');

  out.push('## II. ENTITIES');
  out.push('');
  if (nodes.length === 0) {
    out.push('_No entities recorded._');
  } else {
    out.push('| Entity | Type | Flags | Attributes |');
    out.push('| --- | --- | --- | --- |');
    for (const n of nodes) {
      const attrs = Object.entries(n.attrs ?? {})
        .map(([k, v]) => `${k}=${v ?? '—'}`)
        .join('; ');
      out.push(
        `| ${escapePipes(n.label)} | ${escapePipes(n.type)} | ${n.sanctioned ? '⚠️ SANCTIONED' : '—'} | ${escapePipes(attrs || '—')} |`
      );
    }
  }
  out.push('');

  out.push('## III. RELATIONSHIPS');
  out.push('');
  if (links.length === 0) {
    out.push('_No relationships recorded._');
  } else {
    const byId = new Map(nodes.map((n) => [n.id, n.label]));
    for (const l of links) {
      const a = byId.get(l.source) ?? l.source;
      const b = byId.get(l.target) ?? l.target;
      out.push(`- ${a} **${l.label ?? 'linked to'}** ${b}`);
    }
  }
  out.push('');

  out.push('## IV. SANCTIONS SCREENING');
  out.push('');
  out.push(
    sanctioned.length === 0
      ? 'No mapped entity matched the OFAC SDN list at time of export.'
      : sanctioned.map((n) => `- ⚠️ **${n.label}** (${n.type}) — OFAC SDN match.`).join('\n')
  );
  out.push('');

  if (input.notes?.trim()) {
    out.push('## V. ANALYST NOTES');
    out.push('');
    out.push(input.notes.trim());
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(
    '_Generated by Vantage from open sources. Assessments are analytic judgements, not verified fact._'
  );
  return out.join('\n');
}

/** Minimal Markdown subset renderer — enough for the dossier shapes above. */
function markdownToHtml(md: string): string {
  const lines = md.split('\n');
  const html: string[] = [];
  let inTable = false;

  const inline = (s: string) =>
    s
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/_(.+?)_/g, '<em>$1</em>');

  const closeTable = () => {
    if (inTable) {
      html.push('</tbody></table>');
      inTable = false;
    }
  };

  for (const line of lines) {
    const t = line.trimEnd();
    if (/^\|\s*-{3,}/.test(t)) continue; // separator row
    if (t.startsWith('|')) {
      const cells = t.split('|').slice(1, -1).map((c) => inline(c.trim()));
      if (!inTable) {
        html.push('<table><thead><tr>' + cells.map((c) => `<th>${c}</th>`).join('') + '</tr></thead><tbody>');
        inTable = true;
      } else {
        html.push('<tr>' + cells.map((c) => `<td>${c}</td>`).join('') + '</tr>');
      }
      continue;
    }
    closeTable();
    if (t.startsWith('### ')) html.push(`<h3>${inline(t.slice(4))}</h3>`);
    else if (t.startsWith('## ')) html.push(`<h2>${inline(t.slice(3))}</h2>`);
    else if (t.startsWith('# ')) html.push(`<h1>${inline(t.slice(2))}</h1>`);
    else if (t.startsWith('- ')) html.push(`<li>${inline(t.slice(2))}</li>`);
    else if (t === '---') html.push('<hr/>');
    else if (t === '') html.push('');
    else html.push(`<p>${inline(t.replace(/ {2}$/, ''))}</p>`);
  }
  closeTable();
  return html.join('\n');
}

const PRINT_CSS = `
  @page { size: A4; margin: 18mm 16mm; }
  body { font: 12px/1.55 ui-sans-serif, system-ui, "Segoe UI", sans-serif; color: #111; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
  h1 { font-size: 22px; border-bottom: 2px solid #111; padding-bottom: .4rem; letter-spacing: .04em; }
  h2 { font-size: 15px; margin-top: 1.8rem; letter-spacing: .06em; text-transform: uppercase; }
  table { border-collapse: collapse; width: 100%; margin: .6rem 0; font-size: 11px; }
  th, td { border: 1px solid #bbb; padding: .35rem .5rem; text-align: left; vertical-align: top; }
  th { background: #f0f0f0; }
  li { margin-left: 1rem; }
  hr { border: 0; border-top: 1px solid #ccc; margin: 2rem 0 1rem; }
  @media print { body { margin: 0; max-width: none; } }
`;

/**
 * Print-ready HTML. Served with Content-Disposition inline so the operator
 * can hit Ctrl+P → Save as PDF, which is the PDF export path.
 */
export function renderHtml(input: DossierInput): string {
  const md = renderMarkdown(input);
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>VANTAGE DOSSIER — ${input.name.replace(/[<>&]/g, '')}</title>
<style>${PRINT_CSS}</style>
</head><body>
${markdownToHtml(md)}
</body></html>`;
}
